// <auto-generated />
using System;
using MedResearch.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MedResearch.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MedResearchDbContext))]
    [Migration("20260902031207_AllowMultipleDiscoveryPathsPerStudy")]
    partial class AllowMultipleDiscoveryPathsPerStudy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MedResearch.Domain.Evidence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comparator")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("comparator");

                    b.Property<decimal?>("ConfidenceIntervalLower")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("confidence_interval_lower");

                    b.Property<decimal?>("ConfidenceIntervalUpper")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("confidence_interval_upper");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("direction");

                    b.Property<string>("EffectMeasure")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("effect_measure");

                    b.Property<decimal?>("EffectValue")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("effect_value");

                    b.Property<Guid>("EvidenceExtractionId")
                        .HasColumnType("uuid")
                        .HasColumnName("evidence_extraction_id");

                    b.Property<string>("ExposureOrIntervention")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("exposure_or_intervention");

                    b.Property<DateTimeOffset>("ExtractedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("extracted_at");

                    b.Property<bool>("GroundingValidated")
                        .HasColumnType("boolean")
                        .HasColumnName("grounding_validated");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("outcome");

                    b.Property<decimal?>("PValue")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("p_value");

                    b.Property<string>("Population")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("population");

                    b.Property<Guid>("ResearchRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("research_run_id");

                    b.Property<string>("ResultSummary")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)")
                        .HasColumnName("result_summary");

                    b.Property<int?>("SampleSize")
                        .HasColumnType("integer")
                        .HasColumnName("sample_size");

                    b.Property<string>("SourceScope")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source_scope");

                    b.Property<string>("StudyDesign")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("study_design");

                    b.Property<Guid>("StudyId")
                        .HasColumnType("uuid")
                        .HasColumnName("study_id");

                    b.Property<string>("SupportingText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("supporting_text");

                    b.HasKey("Id");

                    b.HasIndex("EvidenceExtractionId")
                        .HasDatabaseName("ix_evidence_evidence_extraction_id");

                    b.HasIndex("ResearchRunId")
                        .HasDatabaseName("ix_evidence_research_run_id");

                    b.HasIndex("StudyId")
                        .HasDatabaseName("ix_evidence_study_id");

                    b.ToTable("evidence", (string)null);
                });

            modelBuilder.Entity("MedResearch.Domain.EvidenceEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AllocationConcealment")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("allocation_concealment");

                    b.Property<string>("AttritionMissingData")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("attrition_missing_data");

                    b.PrimitiveCollection<string[]>("AuthorReportedLimitations")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("author_reported_limitations");

                    b.Property<string>("Blinding")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("blinding");

                    b.Property<string>("ComparatorDescription")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("comparator_description");

                    b.Property<string>("ComparatorPresence")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("comparator_presence");

                    b.Property<string>("Directness")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("directness");

                    b.Property<DateTimeOffset>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evaluated_at");

                    b.Property<string>("EvaluatorModel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("evaluator_model");

                    b.Property<string>("EvaluatorProvider")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("evaluator_provider");

                    b.PrimitiveCollection<Guid[]>("EvidenceIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("evidence_ids");

                    b.Property<bool>("HasComparator")
                        .HasColumnType("boolean")
                        .HasColumnName("has_comparator");

                    b.Property<bool>("HasConfidenceInterval")
                        .HasColumnType("boolean")
                        .HasColumnName("has_confidence_interval");

                    b.Property<bool>("HasEffectEstimate")
                        .HasColumnType("boolean")
                        .HasColumnName("has_effect_estimate");

                    b.Property<bool>("HasPValue")
                        .HasColumnType("boolean")
                        .HasColumnName("has_p_value");

                    b.Property<bool>("HasSampleSize")
                        .HasColumnType("boolean")
                        .HasColumnName("has_sample_size");

                    b.Property<int>("InsufficientSourceDomainCount")
                        .HasColumnType("integer")
                        .HasColumnName("insufficient_source_domain_count");

                    b.Property<string>("OverallConfidence")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("overall_confidence");

                    b.Property<string>("Precision")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("precision");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("prompt_version");

                    b.Property<string>("Randomization")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("randomization");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("rationale");

                    b.PrimitiveCollection<string[]>("ReportingLimitations")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("reporting_limitations");

                    b.Property<Guid>("ResearchRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("research_run_id");

                    b.Property<string>("SampleInformation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sample_information");

                    b.Property<string>("SkipReason")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("skip_reason");

                    b.Property<string>("SourceScope")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source_scope");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("StudyDesign")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("study_design");

                    b.Property<Guid>("StudyId")
                        .HasColumnType("uuid")
                        .HasColumnName("study_id");

                    b.Property<int>("UnknownDomainCount")
                        .HasColumnType("integer")
                        .HasColumnName("unknown_domain_count");

                    b.HasKey("Id");

                    b.HasIndex("StudyId")
                        .HasDatabaseName("ix_evidence_evaluations_study_id");

                    b.HasIndex("ResearchRunId", "Status")
                        .HasDatabaseName("ix_evidence_evaluations_research_run_id_status");

                    b.HasIndex("ResearchRunId", "StudyId", "PromptVersion")
                        .IsUnique()
                        .HasDatabaseName("ux_evidence_evaluations_research_run_id_study_id_prompt_version");

                    b.ToTable("evidence_evaluations", (string)null);
                });

            modelBuilder.Entity("MedResearch.Domain.EvidenceExtraction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("EvidenceCount")
                        .HasColumnType("integer")
                        .HasColumnName("evidence_count");

                    b.Property<DateTimeOffset>("ExtractedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("extracted_at");

                    b.Property<bool>("GroundingValidated")
                        .HasColumnType("boolean")
                        .HasColumnName("grounding_validated");

                    b.Property<string>("Model")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("prompt_version");

                    b.Property<string>("Provider")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider");

                    b.Property<Guid>("ResearchRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("research_run_id");

                    b.Property<string>("SkipReason")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("skip_reason");

                    b.Property<string>("SourceScope")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source_scope");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("StudyId")
                        .HasColumnType("uuid")
                        .HasColumnName("study_id");

                    b.HasKey("Id");

                    b.HasIndex("StudyId")
                        .HasDatabaseName("ix_evidence_extractions_study_id");

                    b.HasIndex("ResearchRunId", "Status")
                        .HasDatabaseName("ix_evidence_extractions_research_run_id_status");

                    b.HasIndex("ResearchRunId", "StudyId", "PromptVersion")
                        .IsUnique()
                        .HasDatabaseName("ux_evidence_extractions_research_run_id_study_id_prompt_version");

                    b.ToTable("evidence_extractions", (string)null);
                });

            modelBuilder.Entity("MedResearch.Domain.LiteratureSearch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DuplicateStudyCount")
                        .HasColumnType("integer")
                        .HasColumnName("duplicate_study_count");

                    b.Property<int>("PersistedStudyCount")
                        .HasColumnType("integer")
                        .HasColumnName("persisted_study_count");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("query");

                    b.Property<Guid?>("ResearchPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("research_plan_id");

                    b.Property<Guid>("ResearchRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("research_run_id");

                    b.Property<int>("ResultCount")
                        .HasColumnType("integer")
                        .HasColumnName("result_count");

                    b.Property<DateTimeOffset>("SearchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("searched_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("ResearchPlanId")
                        .HasDatabaseName("ix_literature_searches_research_plan_id");

                    b.HasIndex("ResearchRunId", "SearchedAt")
                        .HasDatabaseName("ix_literature_searches_research_run_id_searched_at");

                    b.ToTable("literature_searches", (string)null);
                });

            modelBuilder.Entity("MedResearch.Domain.ResearchPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comparator")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("comparator");

                    b.PrimitiveCollection<string[]>("ExclusionHints")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("exclusion_hints");

                    b.Property<string>("ExposureOrIntervention")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("exposure_or_intervention");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model");

                    b.Property<string>("OriginalQuestion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("original_question");

                    b.PrimitiveCollection<string[]>("Outcomes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("outcomes");

                    b.Property<string>("Population")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("population");

                    b.PrimitiveCollection<string[]>("PreferredStudyTypes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("preferred_study_types");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("prompt_version");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider");

                    b.Property<Guid>("ResearchQuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("research_question_id");

                    b.Property<Guid>("ResearchRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("research_run_id");

                    b.PrimitiveCollection<string[]>("SearchQueries")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("search_queries");

                    b.HasKey("Id");

                    b.HasIndex("ResearchQuestionId")
                        .HasDatabaseName("ix_research_plans_research_question_id");

                    b.HasIndex("ResearchRunId")
                        .IsUnique()
                        .HasDatabaseName("ux_research_plans_research_run_id");

                    b.ToTable("research_plans", (string)null);
                });

            modelBuilder.Entity("MedResearch.Domain.ResearchQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.ToTable("research_questions", (string)null);
                });

            modelBuilder.Entity("MedResearch.Domain.ResearchReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ClaimCount")
                        .HasColumnType("integer")
                        .HasColumnName("claim_count");

                    b.Property<string>("Conclusion")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .HasColumnType("character varying(2500)")
                        .HasColumnName("conclusion");

                    b.Property<string>("ConflictSummary")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .HasColumnType("character varying(2500)")
                        .HasColumnName("conflict_summary");

                    b.PrimitiveCollection<string[]>("DeterministicLimitations")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("deterministic_limitations");

                    b.Property<int>("DiscoveredStudyCount")
                        .HasColumnType("integer")
                        .HasColumnName("discovered_study_count");

                    b.Property<int>("EvaluatedStudyCount")
                        .HasColumnType("integer")
                        .HasColumnName("evaluated_study_count");

                    b.Property<int>("EvidenceFindingCount")
                        .HasColumnType("integer")
                        .HasColumnName("evidence_finding_count");

                    b.Property<string>("EvidenceSummary")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .HasColumnType("character varying(2500)")
                        .HasColumnName("evidence_summary");

                    b.Property<bool>("EvidenceTruncated")
                        .HasColumnType("boolean")
                        .HasColumnName("evidence_truncated");

                    b.Property<string>("ExecutiveSummary")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .HasColumnType("character varying(2500)")
                        .HasColumnName("executive_summary");

                    b.Property<int>("ExtractedStudyCount")
                        .HasColumnType("integer")
                        .HasColumnName("extracted_study_count");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<int>("IncludedEvidenceFindingCount")
                        .HasColumnType("integer")
                        .HasColumnName("included_evidence_finding_count");

                    b.Property<int>("IncludedStudyCount")
                        .HasColumnType("integer")
                        .HasColumnName("included_study_count");

                    b.Property<string>("InsufficientEvidenceReason")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("insufficient_evidence_reason");

                    b.Property<string>("LimitationsSummary")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .HasColumnType("character varying(2500)")
                        .HasColumnName("limitations_summary");

                    b.Property<bool>("PotentialConflictDetected")
                        .HasColumnType("boolean")
                        .HasColumnName("potential_conflict_detected");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("prompt_version");

                    b.Property<Guid>("ResearchRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("research_run_id");

                    b.Property<int>("SearchQueryCount")
                        .HasColumnType("integer")
                        .HasColumnName("search_query_count");

                    b.PrimitiveCollection<string[]>("SearchedSources")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("searched_sources");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<int>("StudiesWithInsufficientEvaluationSource")
                        .HasColumnType("integer")
                        .HasColumnName("studies_with_insufficient_evaluation_source");

                    b.Property<int>("StudiesWithNoExtractableEvidence")
                        .HasColumnType("integer")
                        .HasColumnName("studies_with_no_extractable_evidence");

                    b.Property<string>("SynthesisConfidence")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("synthesis_confidence");

                    b.Property<string>("SynthesizerModel")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("synthesizer_model");

                    b.Property<string>("SynthesizerProvider")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("synthesizer_provider");

                    b.Property<bool>("UsesAbstractLevelEvidenceOnly")
                        .HasColumnType("boolean")
                        .HasColumnName("uses_abstract_level_evidence_only");

                    b.HasKey("Id");

                    b.HasIndex("ResearchRunId", "PromptVersion")
                        .IsUnique()
                        .HasDatabaseName("ux_research_reports_research_run_id_prompt_version");

                    b.HasIndex("ResearchRunId", "Status")
                        .HasDatabaseName("ix_research_reports_research_run_id_status");

                    b.ToTable("research_reports", (string)null);
                });

            modelBuilder.Entity("MedResearch.Domain.ResearchReportClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("claim_type");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("direction");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.Property<Guid>("ResearchReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("research_report_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("ResearchReportId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ux_research_report_claims_research_report_id_ordinal");

                    b.ToTable("research_report_claims", (string)null);
                });

            modelBuilder.Entity("MedResearch.Domain.ResearchReportClaimEvidence", b =>
                {
                    b.Property<Guid>("ResearchReportClaimId")
                        .HasColumnType("uuid")
                        .HasColumnName("research_report_claim_id");

                    b.Property<Guid>("EvidenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("evidence_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer")
                        .HasColumnName("ordinal");

                    b.HasKey("ResearchReportClaimId", "EvidenceId");

                    b.HasIndex("EvidenceId")
                        .HasDatabaseName("ix_research_report_claim_evidence_evidence_id");

                    b.HasIndex("ResearchReportClaimId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("ux_research_report_claim_evidence_claim_id_ordinal");

                    b.ToTable("research_report_claim_evidence", (string)null);
                });

            modelBuilder.Entity("MedResearch.Domain.ResearchRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_reason");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_at");

                    b.Property<DateTimeOffset?>("ProcessingLeaseAcquiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processing_lease_acquired_at");

                    b.Property<DateTimeOffset?>("ProcessingLeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processing_lease_expires_at");

                    b.Property<string>("ProcessingLeaseOwner")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("processing_lease_owner");

                    b.Property<long>("ProcessingLeaseVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("processing_lease_version");

                    b.Property<Guid>("ResearchQuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("research_question_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ResearchQuestionId");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_research_runs_status_created_at");

                    b.HasIndex("Status", "ProcessingLeaseExpiresAt", "CreatedAt")
                        .HasDatabaseName("ix_research_runs_status_lease_expires_at_created_at");

                    b.ToTable("research_runs", (string)null);
                });

            modelBuilder.Entity("MedResearch.Domain.ResearchStudyDiscovery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("DiscoveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discovered_at");

                    b.Property<Guid>("LiteratureSearchId")
                        .HasColumnType("uuid")
                        .HasColumnName("literature_search_id");

                    b.Property<Guid>("ResearchRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("research_run_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source");

                    b.Property<string>("SourceStudyIdentifier")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_study_identifier");

                    b.Property<Guid>("StudyId")
                        .HasColumnType("uuid")
                        .HasColumnName("study_id");

                    b.HasKey("Id");

                    b.HasIndex("LiteratureSearchId")
                        .HasDatabaseName("ix_research_study_discoveries_literature_search_id");

                    b.HasIndex("StudyId")
                        .HasDatabaseName("ix_research_study_discoveries_study_id");

                    b.HasIndex("LiteratureSearchId", "StudyId")
                        .IsUnique()
                        .HasDatabaseName("ux_research_study_discoveries_literature_search_id_study_id");

                    b.HasIndex("ResearchRunId", "StudyId")
                        .HasDatabaseName("ix_research_study_discoveries_research_run_id_study_id");

                    b.ToTable("research_study_discoveries", (string)null);
                });

            modelBuilder.Entity("MedResearch.Domain.Study", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Abstract")
                        .HasColumnType("text")
                        .HasColumnName("abstract");

                    b.PrimitiveCollection<string[]>("Authors")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("authors");

                    b.Property<string>("Doi")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("doi");

                    b.Property<string>("Journal")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("journal");

                    b.Property<string>("Pmid")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("pmid");

                    b.Property<DateOnly?>("PublicationDate")
                        .HasColumnType("date")
                        .HasColumnName("publication_date");

                    b.Property<int?>("PublicationDay")
                        .HasColumnType("integer")
                        .HasColumnName("publication_day");

                    b.Property<int?>("PublicationMonth")
                        .HasColumnType("integer")
                        .HasColumnName("publication_month");

                    b.PrimitiveCollection<string[]>("PublicationTypes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("publication_types");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("integer")
                        .HasColumnName("publication_year");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("Doi")
                        .IsUnique()
                        .HasDatabaseName("ux_studies_doi")
                        .HasFilter("doi IS NOT NULL");

                    b.HasIndex("Pmid")
                        .IsUnique()
                        .HasDatabaseName("ux_studies_pmid")
                        .HasFilter("pmid IS NOT NULL");

                    b.ToTable("studies", (string)null);
                });

            modelBuilder.Entity("MedResearch.Domain.Evidence", b =>
                {
                    b.HasOne("MedResearch.Domain.EvidenceExtraction", null)
                        .WithMany()
                        .HasForeignKey("EvidenceExtractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedResearch.Domain.ResearchRun", null)
                        .WithMany()
                        .HasForeignKey("ResearchRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedResearch.Domain.Study", null)
                        .WithMany()
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MedResearch.Domain.EvidenceEvaluation", b =>
                {
                    b.HasOne("MedResearch.Domain.ResearchRun", null)
                        .WithMany()
                        .HasForeignKey("ResearchRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedResearch.Domain.Study", null)
                        .WithMany()
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MedResearch.Domain.EvidenceExtraction", b =>
                {
                    b.HasOne("MedResearch.Domain.ResearchRun", null)
                        .WithMany()
                        .HasForeignKey("ResearchRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedResearch.Domain.Study", null)
                        .WithMany()
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MedResearch.Domain.LiteratureSearch", b =>
                {
                    b.HasOne("MedResearch.Domain.ResearchPlan", null)
                        .WithMany()
                        .HasForeignKey("ResearchPlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MedResearch.Domain.ResearchRun", null)
                        .WithMany()
                        .HasForeignKey("ResearchRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MedResearch.Domain.ResearchPlan", b =>
                {
                    b.HasOne("MedResearch.Domain.ResearchQuestion", null)
                        .WithMany()
                        .HasForeignKey("ResearchQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedResearch.Domain.ResearchRun", null)
                        .WithMany()
                        .HasForeignKey("ResearchRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MedResearch.Domain.ResearchReport", b =>
                {
                    b.HasOne("MedResearch.Domain.ResearchRun", null)
                        .WithMany()
                        .HasForeignKey("ResearchRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MedResearch.Domain.ResearchReportClaim", b =>
                {
                    b.HasOne("MedResearch.Domain.ResearchReport", null)
                        .WithMany()
                        .HasForeignKey("ResearchReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedResearch.Domain.ResearchReportClaimEvidence", b =>
                {
                    b.HasOne("MedResearch.Domain.Evidence", null)
                        .WithMany()
                        .HasForeignKey("EvidenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedResearch.Domain.ResearchReportClaim", null)
                        .WithMany()
                        .HasForeignKey("ResearchReportClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedResearch.Domain.ResearchRun", b =>
                {
                    b.HasOne("MedResearch.Domain.ResearchQuestion", null)
                        .WithMany()
                        .HasForeignKey("ResearchQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MedResearch.Domain.ResearchStudyDiscovery", b =>
                {
                    b.HasOne("MedResearch.Domain.LiteratureSearch", null)
                        .WithMany()
                        .HasForeignKey("LiteratureSearchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedResearch.Domain.ResearchRun", null)
                        .WithMany()
                        .HasForeignKey("ResearchRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedResearch.Domain.Study", null)
                        .WithMany()
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
