// <auto-generated />
using System;
using MedResearch.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MedResearch.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MedResearchDbContext))]
    [Migration("20260830114130_AddLiteratureSearchProvenance")]
    partial class AddLiteratureSearchProvenance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MedResearch.Domain.Evidence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Claim")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("claim");

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confidence");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("direction");

                    b.Property<Guid>("StudyId")
                        .HasColumnType("uuid")
                        .HasColumnName("study_id");

                    b.HasKey("Id");

                    b.HasIndex("StudyId");

                    b.ToTable("evidence", (string)null);
                });

            modelBuilder.Entity("MedResearch.Domain.LiteratureSearch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DuplicateStudyCount")
                        .HasColumnType("integer")
                        .HasColumnName("duplicate_study_count");

                    b.Property<int>("PersistedStudyCount")
                        .HasColumnType("integer")
                        .HasColumnName("persisted_study_count");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("query");

                    b.Property<Guid>("ResearchRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("research_run_id");

                    b.Property<int>("ResultCount")
                        .HasColumnType("integer")
                        .HasColumnName("result_count");

                    b.Property<DateTimeOffset>("SearchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("searched_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("ResearchRunId", "SearchedAt")
                        .HasDatabaseName("ix_literature_searches_research_run_id_searched_at");

                    b.ToTable("literature_searches", (string)null);
                });

            modelBuilder.Entity("MedResearch.Domain.ResearchQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.ToTable("research_questions", (string)null);
                });

            modelBuilder.Entity("MedResearch.Domain.ResearchRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_reason");

                    b.Property<Guid>("ResearchQuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("research_question_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ResearchQuestionId");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_research_runs_status_created_at");

                    b.ToTable("research_runs", (string)null);
                });

            modelBuilder.Entity("MedResearch.Domain.ResearchStudyDiscovery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("DiscoveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discovered_at");

                    b.Property<Guid>("LiteratureSearchId")
                        .HasColumnType("uuid")
                        .HasColumnName("literature_search_id");

                    b.Property<Guid>("ResearchRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("research_run_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source");

                    b.Property<string>("SourceStudyIdentifier")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source_study_identifier");

                    b.Property<Guid>("StudyId")
                        .HasColumnType("uuid")
                        .HasColumnName("study_id");

                    b.HasKey("Id");

                    b.HasIndex("LiteratureSearchId")
                        .HasDatabaseName("ix_research_study_discoveries_literature_search_id");

                    b.HasIndex("StudyId")
                        .HasDatabaseName("ix_research_study_discoveries_study_id");

                    b.HasIndex("ResearchRunId", "StudyId")
                        .IsUnique()
                        .HasDatabaseName("ux_research_study_discoveries_research_run_id_study_id");

                    b.ToTable("research_study_discoveries", (string)null);
                });

            modelBuilder.Entity("MedResearch.Domain.Study", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Abstract")
                        .HasColumnType("text")
                        .HasColumnName("abstract");

                    b.PrimitiveCollection<string[]>("Authors")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("authors");

                    b.Property<string>("Doi")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("doi");

                    b.Property<string>("Journal")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("journal");

                    b.Property<string>("Pmid")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("pmid");

                    b.Property<DateOnly?>("PublicationDate")
                        .HasColumnType("date")
                        .HasColumnName("publication_date");

                    b.Property<int?>("PublicationDay")
                        .HasColumnType("integer")
                        .HasColumnName("publication_day");

                    b.Property<int?>("PublicationMonth")
                        .HasColumnType("integer")
                        .HasColumnName("publication_month");

                    b.PrimitiveCollection<string[]>("PublicationTypes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("publication_types");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("integer")
                        .HasColumnName("publication_year");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("Doi")
                        .IsUnique()
                        .HasDatabaseName("ux_studies_doi")
                        .HasFilter("doi IS NOT NULL");

                    b.HasIndex("Pmid")
                        .IsUnique()
                        .HasDatabaseName("ux_studies_pmid")
                        .HasFilter("pmid IS NOT NULL");

                    b.ToTable("studies", (string)null);
                });

            modelBuilder.Entity("MedResearch.Domain.Evidence", b =>
                {
                    b.HasOne("MedResearch.Domain.Study", null)
                        .WithMany()
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedResearch.Domain.LiteratureSearch", b =>
                {
                    b.HasOne("MedResearch.Domain.ResearchRun", null)
                        .WithMany()
                        .HasForeignKey("ResearchRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MedResearch.Domain.ResearchRun", b =>
                {
                    b.HasOne("MedResearch.Domain.ResearchQuestion", null)
                        .WithMany()
                        .HasForeignKey("ResearchQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MedResearch.Domain.ResearchStudyDiscovery", b =>
                {
                    b.HasOne("MedResearch.Domain.LiteratureSearch", null)
                        .WithMany()
                        .HasForeignKey("LiteratureSearchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedResearch.Domain.ResearchRun", null)
                        .WithMany()
                        .HasForeignKey("ResearchRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedResearch.Domain.Study", null)
                        .WithMany()
                        .HasForeignKey("StudyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
